### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jihyungSong** [spaceone-dev/plugin-aws-sns-mon-webhook#40]
Information about this plug-in should be written in the README.

* AWS Service Endpoint (in use)
* Required Authentication Overview
* API List for collecting resources
* Release information

**Comment by stat-kwon** [comment]
As a result of the discussion, README.md should be written in a different form from the existing plug-in.
This is because the AWS API is not used as a structure that is externally called with our webhook URL.

Therefore, We decided to write a brief description of the role and purpose of the SNS webhook 
and include the following two items.
- Supported Alert Services
- Release notes
